FROM eclipse-temurin:21-jre-jammy

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN curl -fsSL "https://downloads.metabase.com/v0.61.2/metabase.jar" -o metabase.jar

ENV MB_PLUGINS_DIR=/plugins

ENTRYPOINT ["java", "-jar", "/app/metabase.jar"]
